# Generated by Django 5.0 on 2024-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50, verbose_name='customer name')),
                ('cemail', models.EmailField(max_length=100)),
                ('cphn', models.CharField(max_length=15)),
                ('rv_date', models.DateField()),
                ('rv_time', models.TimeField()),
                ('ppl_count', models.IntegerField()),
                ('msg', models.TextField(null=True)),
            ],
        ),
    ]
