# Generated by Django 5.0 on 2024-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='uid',
            field=models.BigIntegerField(default=0),
        ),
    ]
