# Generated by Django 5.0 on 2024-01-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reservation_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
    ]
