# Generated by Django 5.0 on 2024-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
