# Generated by Django 5.0 on 2024-01-22 20:38

import userauth.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csn_cat_name', models.CharField(max_length=50, verbose_name='Cuisine category name')),
                ('csn_cat_desc', models.TextField(null=True, verbose_name='Cuisine description')),
                ('csn_cat_image', models.ImageField(blank=True, null=True, upload_to=userauth.utilities.get_file_path)),
            ],
        ),
    ]
