# Generated by Django 5.0 on 2024-01-23 10:24

import userauth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('vid_file', models.FileField(blank=True, null=True, upload_to='videos/%y', validators=[userauth.validators.file_size])),
            ],
        ),
    ]
