# Generated by Django 5.0 on 2024-01-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_prodvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('menu_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.cuisinecategory')),
            ],
        ),
    ]
